### PR TITLE
Revert "Disable f2fs"

### PR DESCRIPTION
**Pull request by ghost**
This reverts commit 387d824f28f1194cd29dbeb22614084256bc766f.

### CODE REVIEW

**Comment by ghost** [comment]
Wouldn't boot, this commit was the issue. It does boot now but it won't connect to data

**Comment by mijuu** [comment]
f2fs is not the problem, you could try this，Android 5.0 need UID-based routing, https://github.com/mijuu/android_kernel_motorola_msm8960-common/commit/d4507ac19132e8dbed6d915ac6add387c666edcd

**Comment by ghost** [comment]
Sorry, I worded that bad. Reverting f2fs fixed it to where it boots. I know f2fs doesn't affect the baseband but something has. And yes, I follow your kernel so it is something else.

**Comment by mijuu** [comment]
Three reasons may cause the down of rild,  try check them as below:

https://github.com/mijuu/android_device_motorola_moto_msm8960_jbbl/commit/0248c1025556e61c7d0cc65d55f4e51892cd0ad6

https://github.com/mijuu/android_hardware_ril/commit/b621c475087517931183984e94d69a7f50cd4a46

https://github.com/mijuu/android_device_motorola_moto_msm8960_jbbl/commit/b55a4a85e6b3a0a58d4d99878fd64c8564cf3fd5

**Comment by ghost** [comment]
Ok thanks man, I am building it now. With those repos/commits

**Comment by ghost** [comment]
Dhacker29 has decided to bring jbbl to lollipop
https://github.com/CyanogenMod/android_device_motorola_moto_msm8960_jbbl/tree/cm-12.0
https://github.com/CyanogenMod/android_kernel_motorola_msm8960-common/tree/cm-12.0

**Pull request closed without merging**
